name: Acquire activation file
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Request manual activation file 🔑 (Manual only, for testing license)
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Unity - Activate
        id: getManualLicenseFile
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        uses: game-ci/unity-request-activation-file@v2
